import push from 'web-push';

// vapid keys generated by web-push on first app run
// push.generateVAPIDKeys();
let vapidKeys = {
  publicKey: 'BCZ_db90I1N02Y99Hb3XSvj1GhWIxxDGAkyqzGTZWJLjiATWKQdns74otZFTfCPEimoHNxCgoCpvh5Tw5klQ2UQ',
  privateKey: '4UGAqp2rs7d0n96hiLPYbcq7qM2ZVM8E2_y_up6METk'
}

// set vapid details for push notifications
push.setVapidDetails('mailto:luka.batarelo@thoughtcap.com;', vapidKeys.publicKey, vapidKeys.privateKey);

// subscription object generated by navigator.serviceWorker.ready.pushManager.subscribe()
let subs = {
    "endpoint":"https://fcm.googleapis.com/fcm/send/d5A0Ap1cbnE:APA91bFm094lG1tNwV1B_tpjH2ftwwz9OtB3V31LPuPxqKFKU0puKL56r8sdkA0Xe-Mq95ER_dRN9BPLKbeqUR77gfmc54iFTkp1J7RwbuwLbNu4bOgZA7qwE0LiVFSC5EsaW4lJDU0I",
    "expirationTime":null,
    "keys": {
        "p256dh":"BN862A2QO0_FyrMMrsYrj8NiDi4t7uenhKE3hrHmbk8nQKG5i1e5DnNXiEjeEt7-FjiPsQzuOw4W6Buizwg4qX4",
        "auth":"bNZjafN4UQyU3CT4JC9bfw"
    }
}

// payload object that will be sent to the client
const payload = {
  notification: {
      title: 'Title',
      body: 'This is my body',
      icon: 'assets/icons/icon-384x384.png',
      data: {
          link: 'https://agreeable-sand-037458503.5.azurestaticapps.net/asset-detail/00000001'
      },
  },
};

// send push notification to the client - subscription object and stringified (or Buffered) payload required
push.sendNotification(subs, JSON.stringify(payload));